### ISSUE TITLE
[User] crypt email for security reasons

### ISSUE THREAD

**Issue by Bizarrus** [fruithost/Panel#1]
Create a `SALT` and hash `email` adresses in the database for security reasons.

**Comment by Christian1998** [comment]
Hey Adrian, die Frage ist, warum du die Email hashen möchtest? Emails an den Kunden werden dann doch nichtmehr zustellbar sein? :D
grüsse aus aarau
Christian

**Comment by Bizarrus** [comment]
Hey, danke für die Interesse :)

Die E-Mail wird nicht gehasht, sondern crypted. Wenn die E-Mail Adresse Beispielsweise zum versenden genutzt wird, wird diese anhand des saltes wieder in Plain entschlüsselt.

Klar, man kann dadrüber streiten, dass jemand, der Zugriff auf dem kompletten Server besitzt, auch die Daten wiederherstellen könnte. Dies ist aber eine Vorsichtsmaßnahme gegenüber SQL-Injections oder einen zufällig auf dem Datenbank-Server gelungenen Zugriff. Der Angreifer müsste dementsprechend physischen Zugriff auf das System haben um den `SALT` herauszufinden.
