### ISSUE TITLE
[Help]  Access to fruithost in localhost

### ISSUE THREAD

**Issue by ghost** [fruithost/Panel#19]
### Question

Hello, I've installed the setup both on an external server and within my local network. The issue I'm encountering is that I can't access the subdomain on my server. Is there a way to gain access to "fruithost" from my IP? For instance, when I access the IP http://192.168.1.104/ within the network, I receive the following error: "The host "" is currently not configured."

Do you have any suggestions?
![Uploading Screenshot 2023-12-23 113854.jpg…]()

**Comment by Bizarrus** [comment]
> [!WARNING]
> Dont share personal informations (for sample, your E-Mail)!
> We dont have premium-support with direct contacting, E-Mail postings will be removed!

Please check the Hostname.

https://github.com/fruithost/Documentation/blob/main/Development/WSL-Development.md#change-hostname

https://github.com/fruithost/Documentation/blob/main/Development/WSL-Development.md#fix-the-hostname
