### ISSUE TITLE
Demonstration

### ISSUE THREAD

**Issue by 021fneves** [fruithost/Panel#20]
### Question

I requested a demo login, but so far I haven't received it, it's been a month.
Why don't you put your demo login and password here on the github page so you can test?

**Comment by Bizarrus** [comment]
Hey,

We do not currently offer a demo version as there is no server available at the moment. The panel is currently running on a normal web space where no hosting features can be tested.

fruithost can be easily installed via [WSL](https://github.com/fruithost/Documentation/blob/main/Development/WSL-Development.md) at any time if you want to try it out:
 - [WSL-Development](https://github.com/fruithost/Documentation/blob/main/Development/WSL-Development.md) 
 - [WSL2](https://github.com/fruithost/Documentation/blob/main/Development/WSL2.md) 

As the development has not been [supported](https://github.com/fruithost#support-us-) by anyone for years, we are unfortunately unable to offer a test server for it at present.

**Comment by 021fneves** [comment]
I understood.
Thanks!
