### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by codedbean** [fruithost/Panel#7]
Is there a documentation on how to install this?

**Comment by Bizarrus** [comment]
The first installable version is currently not available. The software is currently under development.

On **Patreon** i had write following information:

> When I reach $500 per month, I will release the first installable version of fruithost. If the goal is not reached yet, it will take some more time, because i'm a perfectionist!

You can request an demonstration, if you like.

**Comment by codedbean** [comment]
Where can I go to request a demonstration?

**Comment by Bizarrus** [comment]
You can request a demonstration here: https://forms.gle/eS7E4MYSVKiiigw77

**Comment by codedbean** [comment]
Submitted.

**Comment by codedbean** [comment]
Be a team-player, all feedbacks of our patrons will have the priority. "We will build the site for YOU!"

What do you mean by building a website? I'm interested in this.

**Comment by Bizarrus** [comment]
Your account has been created. You can now use the [Lost Password](http://my.fruithost.de/lost-password) function, to set an passwort.

> What do you mean by building a website? I'm interested in this.

The statement means that I program the system.

**Comment by codedbean** [comment]
I've been getting some errors during the demo.
<img width="1080" alt="Screen Shot 2019-06-24 at 7 19 36 PM" src="https://user-images.githubusercontent.com/51534682/60060241-56bd3c00-96b5-11e9-8618-3b7af2e497fd.png">
<img width="1326" alt="Screen Shot 2019-06-24 at 7 20 22 PM" src="https://user-images.githubusercontent.com/51534682/60060242-5755d280-96b5-11e9-88ce-a2956c9c389f.png">

**Comment by Bizarrus** [comment]
Thanks for the feedback, i had solve the problems.

The cache directory of webmailer had no permissions to write the language cache files - I hope it's solved today.

On user account data, the informations will be encrypted - Here i had forgot to check the entries for new users.
