### ISSUE TITLE
 Fatal error: Uncaught Error: Undefined constant

### ISSUE THREAD

**Issue by Fluke667** [fruithost/Panel#9]
Fatal error: Uncaught Error: Undefined constant "fruithost\DATABASE_PREFIX" in /usr/share/nginx/html/lcp/panel/classes/Modules.class.php:12 Stack trace: #0 /usr/share/nginx/html/lcp/panel/classes/Core.class.php(126): fruithost\Modules->__construct() #1 /usr/share/nginx/html/lcp/panel/classes/Core.class.php(14): fruithost\Core->init() #2 /usr/share/nginx/html/lcp/panel/index.php(16): fruithost\Core->__construct() #3 {main} thrown in /usr/share/nginx/html/lcp/panel/classes/Modules.class.php on line 12

**Comment by Bizarrus** [comment]
Your configurations-file is missing.

The configuration will be created on installations process:
[debian.sh#L160](https://github.com/fruithost/Installers/blob/master/debian.sh#L160)

The file is **located** in `/etc/fruithost/.config.php`
```php
<?php
	# Database Connection
	define('DATABASE_HOSTNAME',		'localhost');
	define('DATABASE_PORT',			3306);
	define('DATABASE_USERNAME',		'fruithost');
	define('DATABASE_PASSWORD',		'$mysql_password');
	define('DATABASE_NAME',			'fruithost');
	define('DATABASE_PREFIX',		'fh_');

	# Hosting Path
	define('HOST_PATH',			'/var/fruithost/users/');
?>
```
